"""empty message

Revision ID: c19b44e4a64b
Revises: 
Create Date: 2017-09-07 21:57:01.470777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19b44e4a64b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_city_metro_county_id'), 'city_metro', ['county_id'], unique=False)
    op.create_index(op.f('ix_city_metro_state_id'), 'city_metro', ['state_id'], unique=False)
    op.create_foreign_key(None, 'city_metro', 'county', ['county_id'], ['id'])
    op.create_foreign_key(None, 'city_metro', 'state', ['state_id'], ['id'])
    op.create_index(op.f('ix_county_state_id'), 'county', ['state_id'], unique=False)
    op.create_foreign_key(None, 'county', 'state', ['state_id'], ['id'])
    op.create_index(op.f('ix_menu_restaurant_links_id'), 'menu', ['restaurant_links_id'], unique=False)
    op.create_foreign_key(None, 'menu', 'restaurant_links', ['restaurant_links_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_metro_assoc_state_id'), 'metro_assoc', ['state_id'], unique=False)
    op.create_foreign_key(None, 'metro_assoc', 'state', ['state_id'], ['id'])
    op.create_index(op.f('ix_restaurant_links_city_metro_id'), 'restaurant_links', ['city_metro_id'], unique=False)
    op.create_index(op.f('ix_restaurant_links_county_id'), 'restaurant_links', ['county_id'], unique=False)
    op.create_index(op.f('ix_restaurant_links_state_id'), 'restaurant_links', ['state_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_links', 'county', ['county_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_links', 'city_metro', ['city_metro_id'], ['id'])
    op.create_foreign_key(None, 'restaurant_links', 'state', ['state_id'], ['id'])
    op.create_index(op.f('ix_restaurant_links_cusine_cusine_id'), 'restaurant_links_cusine', ['cusine_id'], unique=False)
    op.create_index(op.f('ix_restaurant_links_cusine_restaurant_links_id'), 'restaurant_links_cusine', ['restaurant_links_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_links_cusine', 'cusine', ['cusine_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_links_cusine', 'restaurant_links', ['restaurant_links_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_restaurant_menu_category_category_id'), 'restaurant_menu_category', ['category_id'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_category_menu_id'), 'restaurant_menu_category', ['menu_id'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_category_restaurant_links_id'), 'restaurant_menu_category', ['restaurant_links_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_menu_category', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_menu_category', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_menu_category', 'restaurant_links', ['restaurant_links_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_restaurant_menu_category_item_category_id'), 'restaurant_menu_category_item', ['category_id'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_category_item_menu_id'), 'restaurant_menu_category_item', ['menu_id'], unique=False)
    op.create_index(op.f('ix_restaurant_menu_category_item_restaurant_links_id'), 'restaurant_menu_category_item', ['restaurant_links_id'], unique=False)
    op.create_foreign_key(None, 'restaurant_menu_category_item', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_menu_category_item', 'menu', ['menu_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'restaurant_menu_category_item', 'restaurant_links', ['restaurant_links_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'state', ['id'])
    op.drop_constraint(u'users_profile_email_key', 'users_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_profile_email_key', 'users_profile', ['email'])
    op.drop_constraint(None, 'state', type_='unique')
    op.drop_constraint(None, 'restaurant_menu_category_item', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_menu_category_item', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_menu_category_item', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_menu_category_item_restaurant_links_id'), table_name='restaurant_menu_category_item')
    op.drop_index(op.f('ix_restaurant_menu_category_item_menu_id'), table_name='restaurant_menu_category_item')
    op.drop_index(op.f('ix_restaurant_menu_category_item_category_id'), table_name='restaurant_menu_category_item')
    op.drop_constraint(None, 'restaurant_menu_category', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_menu_category', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_menu_category', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_menu_category_restaurant_links_id'), table_name='restaurant_menu_category')
    op.drop_index(op.f('ix_restaurant_menu_category_menu_id'), table_name='restaurant_menu_category')
    op.drop_index(op.f('ix_restaurant_menu_category_category_id'), table_name='restaurant_menu_category')
    op.drop_constraint(None, 'restaurant_links_cusine', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_links_cusine', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_links_cusine_restaurant_links_id'), table_name='restaurant_links_cusine')
    op.drop_index(op.f('ix_restaurant_links_cusine_cusine_id'), table_name='restaurant_links_cusine')
    op.drop_constraint(None, 'restaurant_links', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_links', type_='foreignkey')
    op.drop_constraint(None, 'restaurant_links', type_='foreignkey')
    op.drop_index(op.f('ix_restaurant_links_state_id'), table_name='restaurant_links')
    op.drop_index(op.f('ix_restaurant_links_county_id'), table_name='restaurant_links')
    op.drop_index(op.f('ix_restaurant_links_city_metro_id'), table_name='restaurant_links')
    op.drop_constraint(None, 'metro_assoc', type_='foreignkey')
    op.drop_index(op.f('ix_metro_assoc_state_id'), table_name='metro_assoc')
    op.drop_constraint(None, 'menu', type_='foreignkey')
    op.drop_index(op.f('ix_menu_restaurant_links_id'), table_name='menu')
    op.drop_constraint(None, 'county', type_='foreignkey')
    op.drop_index(op.f('ix_county_state_id'), table_name='county')
    op.drop_constraint(None, 'city_metro', type_='foreignkey')
    op.drop_constraint(None, 'city_metro', type_='foreignkey')
    op.drop_index(op.f('ix_city_metro_state_id'), table_name='city_metro')
    op.drop_index(op.f('ix_city_metro_county_id'), table_name='city_metro')
    # ### end Alembic commands ###
