"""empty message

Revision ID: c50b97e01e7e
Revises: 
Create Date: 2017-09-07 22:23:22.735769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50b97e01e7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    
    op.drop_constraint(u'users_profile_email_key', 'users_profile', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'users_profile_email_key', 'users_profile', ['email'])
    
    # ### end Alembic commands ###
